# Generated by Django 4.2.1 on 2023-07-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_car_fabula_remove_car_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fabula',
            field=models.TextField(blank=True, null=True, verbose_name='Фабула'),
        ),
    ]
