# Generated by Django 4.2.1 on 2023-06-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='people',
        ),
    ]
