# Generated by Django 4.2.1 on 2023-06-20 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manuldb', '0005_alter_peopleimage_image_college'),
        ('car', '0002_alter_car_options_car_status_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='file',
        ),
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='initiator',
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='status_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manuldb.case', verbose_name='Номер уголовного дело'),
            preserve_default=False,
        ),
    ]
