# Generated by Django 4.2.1 on 2023-06-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_file_remove_car_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
