# Generated by Django 4.2.1 on 2023-06-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_carimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name': 'Добавить дополнительные фотографии'},
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='image',
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_car',
            field=models.ImageField(default=1, upload_to='src/images/car', verbose_name='Путь к фотографиям'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Фото'),
        ),
    ]
