# Generated by Django 4.2.1 on 2023-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_people_description_people_fabula_people_hobby'),
        ('manuldb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatives',
            name='relatives',
            field=models.ManyToManyField(related_name='related_people', to='people.people', verbose_name='Информация'),
        ),
    ]
