# Generated by Django 4.2.1 on 2023-06-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=250, unique=True, verbose_name='виды')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_number', models.CharField(max_length=250, verbose_name='Номер уголовного дела')),
                ('vid_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuldb.view', verbose_name='Вид преступления')),
            ],
            options={
                'verbose_name': 'номер',
                'verbose_name_plural': 'Номер уголовного дела',
            },
        ),
    ]
