# Generated by Django 4.2.1 on 2023-06-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0002_view_case'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleimage',
            old_name='image',
            new_name='image_college',
        ),
    ]
