# Generated by Django 4.2.1 on 2023-06-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0003_rename_image_peopleimage_image_college'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'verbose_name': 'номер', 'verbose_name_plural': 'Дело'},
        ),
    ]
