# Generated by Django 4.2.1 on 2023-06-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0009_vid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vid',
            options={'verbose_name': 'номер', 'verbose_name_plural': 'Номер уголовного дела'},
        ),
        migrations.AlterField(
            model_name='vid',
            name='vid_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuldb.category', verbose_name='Вид преступления'),
        ),
    ]
