# Generated by Django 4.2.1 on 2023-06-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_remove_relatives_relatives_remove_people_city_and_more'),
        ('manuldb', '0010_alter_vid_options_alter_vid_vid_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='src/images/people')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Relatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кто')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='people.people', verbose_name='Человек')),
                ('relatives', models.ManyToManyField(related_name='related_people', to='people.people', verbose_name='Родственник')),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='city_title',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
