# Generated by Django 4.2.1 on 2023-06-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0011_peopleimage_relatives_remove_state_city_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopleimage',
            options={'verbose_name': 'Добавить дополнительные фотографии'},
        ),
        migrations.AlterField(
            model_name='peopleimage',
            name='image',
            field=models.ImageField(upload_to='src/images/people', verbose_name='Фото'),
        ),
    ]
