# Generated by Django 4.2.1 on 2023-06-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0012_alter_peopleimage_options_alter_peopleimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatives',
            name='relatives',
        ),
    ]
