# Generated by Django 4.2.1 on 2023-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_remove_relatives_relatives_remove_people_city_and_more'),
        ('manuldb', '0013_remove_relatives_relatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatives',
            name='relatives',
            field=models.ManyToManyField(related_name='related_people', to='people.people', verbose_name='Родственник'),
        ),
    ]
