# Generated by Django 4.2.1 on 2023-07-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabula', models.TextField(blank=True, null=True, verbose_name='Фабула')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Марка')),
                ('erp', models.CharField(max_length=255, verbose_name='Номер ЕРП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примичание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('people', models.ManyToManyField(blank=True, null=True, to='people.people', verbose_name='Подозреваемый')),
            ],
            options={
                'verbose_name': 'добавить',
                'verbose_name_plural': 'Данные оружия',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='WeaponsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_car', models.ImageField(upload_to='src/images/цeapons', verbose_name='Путь к фотографиям')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.weapons', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Добавить дополнительные фотографии',
            },
        ),
    ]
