# Generated by Django 4.2.1 on 2023-07-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponsimage',
            name='image_car',
        ),
        migrations.AddField(
            model_name='weaponsimage',
            name='image_weapons',
            field=models.ImageField(default=1, upload_to='src/images/weapons', verbose_name='Путь к фотографиям'),
            preserve_default=False,
        ),
    ]
