# Generated by Django 4.2.1 on 2023-07-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapons',
            name='fabula',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='vid',
        ),
    ]
