# Generated by Django 4.2.1 on 2023-06-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_alter_people_options_alter_people_status_number'),
        ('manuldb', '0005_alter_peopleimage_image_college'),
        ('weapons', '0002_alter_weapons_options_weapons_status_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapons',
            name='file',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='initiator',
        ),
        migrations.RemoveField(
            model_name='weapons',
            name='photo',
        ),
        migrations.AddField(
            model_name='weapons',
            name='people',
            field=models.ManyToManyField(to='people.people', verbose_name='Персон'),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='status_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manuldb.case', verbose_name='Номер уголовного дело'),
            preserve_default=False,
        ),
    ]
