# Generated by Django 4.2.1 on 2023-07-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид преступления')),
                ('fabula', models.CharField(blank=True, max_length=22255, null=True, verbose_name='Фабула')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Марка')),
                ('erp', models.CharField(max_length=255, verbose_name='Ноомер ЕРП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примичание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('people', models.ManyToManyField(blank=True, null=True, to='people.people', verbose_name='Персон')),
            ],
            options={
                'verbose_name': 'добавить',
                'verbose_name_plural': 'Данные украденных вещей',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='src/images/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
