# Generated by Django 4.2.1 on 2023-06-20 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('police', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Серийный номер')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Марка')),
                ('erp', models.CharField(max_length=255, verbose_name='Ноомер ЕРП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примичание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='src/images/product', verbose_name='Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='src/file/product', verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='police.initiator', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'добавить',
                'verbose_name_plural': 'АИС Вещи',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='src/images/product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
    ]
