# Generated by Django 4.2.1 on 2023-06-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0004_alter_view_options'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'добавить', 'verbose_name_plural': 'Данные украденных вещей'},
        ),
        migrations.AddField(
            model_name='product',
            name='status_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuldb.case'),
        ),
    ]
