# Generated by Django 4.2.1 on 2023-07-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_image_productimage_image_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Добавить дополнительные фотографии'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_product',
            field=models.ImageField(upload_to='src/images/product', verbose_name='Путь к фотографиям'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Путь к'),
        ),
    ]
