# Generated by Django 4.2.1 on 2023-06-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_file_alter_product_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='people',
        ),
    ]
