# Generated by Django 4.2.1 on 2023-05-29 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('police', '0001_initial'),
        ('manuldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.DecimalField(decimal_places=0, max_digits=14, unique=True, verbose_name='ИНН')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчества')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Национальность')),
                ('status', models.CharField(choices=[('organization', 'Организатор'), ('glavar', 'Главарь'), ('shesterka', 'Шестерка')], default='organization', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='src/images/people', verbose_name='Фото')),
                ('file', models.FileField(blank=True, null=True, upload_to='src/file/people', verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manuldb.category', verbose_name='Категория')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuldb.state', verbose_name='Область, город, район')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='police.initiator', verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'добавить',
                'verbose_name_plural': 'АИС Персоны',
            },
        ),
    ]
