# Generated by Django 4.2.1 on 2023-07-03 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид преступления')),
                ('fabula1', models.CharField(blank=True, max_length=22255, null=True, verbose_name='Фабула')),
                ('image', models.ImageField(blank=True, null=True, upload_to='src/images/people', verbose_name='Фото')),
                ('inn', models.DecimalField(decimal_places=0, max_digits=14, unique=True, verbose_name='ИНН')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Национальность')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'добавить',
                'verbose_name_plural': 'Данные подозреваемого',
                'ordering': ['-created'],
            },
        ),
    ]
