# Generated by Django 4.2.1 on 2023-06-20 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='src/images/people', verbose_name='Фото')),
                ('inn', models.DecimalField(decimal_places=0, max_digits=14, unique=True, verbose_name='ИНН')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата рождения')),
                ('nationality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Национальность')),
                ('status', models.CharField(choices=[('Ещё не установлено', 'Ещё не установлено'), ('Возбуждено', 'Возбуждено'), ('Остановлено', 'Остановлено'), ('Передано в суд', 'Передано в суд')], default='Ещё не установлено', max_length=20, verbose_name='Статус дела')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'добавить',
                'verbose_name_plural': 'АИС Персоны',
                'ordering': ['-created'],
            },
        ),
    ]
