# Generated by Django 4.2.1 on 2023-07-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='fabula1',
        ),
        migrations.RemoveField(
            model_name='people',
            name='vid1',
        ),
    ]
