# Generated by Django 4.2.1 on 2023-05-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('organization', 'Организатор'), ('glavar', 'Главарь'), ('shesterka', 'Шестерка')], default='organization', max_length=20, verbose_name='Статус'),
        ),
    ]
