# Generated by Django 4.2.1 on 2023-06-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0002_view_case'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='status_number',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='manuldb.case', verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
