# Generated by Django 4.2.1 on 2023-06-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0004_alter_view_options'),
        ('people', '0002_people_status_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-created'], 'verbose_name': 'добавить', 'verbose_name_plural': 'Данные подозреваемого'},
        ),
        migrations.AlterField(
            model_name='people',
            name='status_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuldb.case', verbose_name='Номер уголовного дело'),
        ),
    ]
