# Generated by Django 4.2.1 on 2023-07-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_people_fabula1_remove_people_vid1'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Примичание'),
        ),
        migrations.AddField(
            model_name='people',
            name='fabula',
            field=models.TextField(blank=True, null=True, verbose_name='Фабула'),
        ),
        migrations.AddField(
            model_name='people',
            name='hobby',
            field=models.TextField(blank=True, null=True, verbose_name='Хобби'),
        ),
    ]
