# Generated by Django 4.2.1 on 2023-06-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_people_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='src/images/people')),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people', verbose_name='Фото')),
            ],
        ),
    ]
