# Generated by Django 4.2.1 on 2023-06-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0006_category_title_number'),
        ('people', '0003_peopleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='category',
        ),
        migrations.AddField(
            model_name='people',
            name='category',
            field=models.ManyToManyField(to='manuldb.category', verbose_name='Категория'),
        ),
    ]
