# Generated by Django 4.2.1 on 2023-06-14 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0008_alter_category_title_category_alter_city_title_city_and_more'),
        ('people', '0004_remove_people_category_people_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='category',
        ),
        migrations.AddField(
            model_name='people',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='manuldb.category', verbose_name='Виды'),
            preserve_default=False,
        ),
    ]
