# Generated by Django 4.2.1 on 2023-06-14 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuldb', '0009_vid'),
        ('people', '0005_remove_people_category_people_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='category',
        ),
        migrations.AddField(
            model_name='people',
            name='vidy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='manuldb.vid', verbose_name='Виды'),
            preserve_default=False,
        ),
    ]
