# Generated by Django 4.2.1 on 2023-06-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_people'),
        ('car', '0003_remove_car_people'),
        ('weapons', '0003_remove_weapons_people'),
        ('people', '0006_remove_people_category_people_vidy'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='car',
            field=models.ManyToManyField(null=True, to='car.car', verbose_name='Налличии машины'),
        ),
        migrations.AddField(
            model_name='people',
            name='products',
            field=models.ManyToManyField(null=True, to='product.product', verbose_name='Наличии предметов'),
        ),
        migrations.AddField(
            model_name='people',
            name='weapon',
            field=models.ManyToManyField(null=True, to='weapons.weapons', verbose_name='Наличии оружия'),
        ),
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('organization', 'Возбуждено'), ('glavar', 'Остановлено'), ('shesterka', 'Переданно в суд')], default='organization', max_length=20, verbose_name='Статус дела'),
        ),
    ]
