# Generated by Django 4.2.1 on 2023-06-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_car_people'),
        ('weapons', '0003_remove_weapons_people'),
        ('product', '0004_remove_product_people'),
        ('people', '0007_people_car_people_products_people_weapon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='car',
        ),
        migrations.RemoveField(
            model_name='people',
            name='products',
        ),
        migrations.RemoveField(
            model_name='people',
            name='weapon',
        ),
        migrations.AddField(
            model_name='people',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Налличии машины'),
        ),
        migrations.AddField(
            model_name='people',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Наличии предметов'),
        ),
        migrations.AddField(
            model_name='people',
            name='weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weapons.weapons', verbose_name='Наличии оружия'),
        ),
    ]
