# Generated by Django 4.2.1 on 2023-06-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_people_car_alter_people_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['-created'], 'verbose_name': 'добавить', 'verbose_name_plural': 'АИС Персоны'},
        ),
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('not', 'Ещё не установлено'), ('organization', 'Возбуждено'), ('glavar', 'Остановлено'), ('shesterka', 'Переданно в суд')], default='not', max_length=20, verbose_name='Статус дела'),
        ),
    ]
