# Generated by Django 4.2.1 on 2023-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_alter_people_options_alter_people_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('Ещё не установлено', 'Ещё не установлено'), ('Возбуждено', 'Возбуждено'), ('Остановлено', 'Остановлено'), ('Переданно в суд', 'Переданно в суд')], default='Ещё не установлено', max_length=20, verbose_name='Статус дела'),
        ),
    ]
