# Generated by Django 4.2.1 on 2023-06-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_remove_people_car_remove_people_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatives',
            name='relatives',
        ),
        migrations.AddField(
            model_name='relatives',
            name='relatives',
            field=models.ManyToManyField(to='people.people', verbose_name='Родственник'),
        ),
    ]
