# Generated by Django 4.2.1 on 2023-06-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_remove_relatives_relatives_relatives_relatives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatives',
            name='relatives',
        ),
        migrations.RemoveField(
            model_name='people',
            name='city',
        ),
        migrations.RemoveField(
            model_name='people',
            name='file',
        ),
        migrations.RemoveField(
            model_name='people',
            name='vidy',
        ),
        migrations.AlterField(
            model_name='people',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('Ещё не установлено', 'Ещё не установлено'), ('Возбуждено', 'Возбуждено'), ('Остановлено', 'Остановлено'), ('Передано в суд', 'Передано в суд')], default='Ещё не установлено', max_length=20, verbose_name='Статус дела'),
        ),
        migrations.DeleteModel(
            name='PeopleImage',
        ),
        migrations.DeleteModel(
            name='Relatives',
        ),
    ]
